### ISSUE TITLE
Non-desirable comma in the generated file

### ISSUE THREAD

**Issue by ClaudioRubattu** [COMPA-Runtime/Spider#21]
It seems that a comma is printed in the "pi_top.cpp", even if no static parameter is present in the ".pi".
In the general case, I obtain a code like this:
```
/* Top graph definition */
top(topVertex, );
```
Of course, this fact leads to a compilation error. Deleting the comma, compilation can finish successfully.
I noticed that, if there is at least one static parameter, the generated code is well printed, and no comma is added after the name of this parameter (the last argument).

**Comment by farresti** [comment]
Preesm related issue: preesm/preesm#271
